name: Build 

#on: [push, pull_request]
on:
  push:
    tags:        
      - '**'

env:
  #CIBW_BUILD_FRONTEND: "pip; args: --no-build-isolation"
  CIBW_BUILD: cp38-win_amd64 cp39-* cp310-* cp311-* cp312-*
  CIBW_SKIP: cp37-* cp38-macosx* 
  CIBW_ARCHS_WINDOWS: "AMD64"
  CIBW_ARCHS_MACOS: "x86_64 arm64"
  CIBW_ARCHS_LINUX: "x86_64"
  CIBW_ENVIRONMENT_MACOS: CFLAGS='-arch x86_64 -arch arm64' CXXFLAGS='-arch x86_64 -arch arm64'
  CIBW_BEFORE_BUILD_WINDOWS: python .github/workflows/prepwin.py && python -m pip install numpy cython
  CIBW_BEFORE_BUILD_MACOS: python -m pip install numpy cython
  CIBW_BEFORE_BUILD_LINUX: python -m pip install numpy cython

jobs:
  build_wheels:
    
    permissions:
      contents: write
    
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0, windows-2022]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies for macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install llvm libomp
          bash .github/workflows/prepmacos.sh

      - name: Install dependencies
        run: python -m pip install attrdict3 wxpython numpy vtk h5py pillow requests cython

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels - macOS
        if: startsWith(matrix.os, 'macos')
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ENVIRONMENT: CFLAGS='-arch x86_64 -arch arm64' CXXFLAGS='-arch x86_64 -arch arm64'
          CC: /usr/local/opt/llvm/bin/clang
          CXX: /usr/local/opt/llvm/bin/clang
          C_INCLUDE_PATH: /usr/local/include
          CPLUS_INCLUDE_PATH: /usr/local/include
          LIBRARY_PATH: /usr/local/lib


      - name: Build wheels - Windows
        if: startsWith(matrix.os, 'windows')
        run: python -m cibuildwheel --output-dir wheelhouse


      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
      
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: ./wheelhouse/*.whl

  build_sdist:
    
    permissions:
      contents: write
    
    name: Build source package
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
  
      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install build
          python -m pip install attrdict3
          python -m pip install wxpython numpy vtk h5py pillow requests cython

      - name: Build sdist
        run: |
          python -m build --sdist
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
      
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: ./dist/*


