name: Build 

on: [push, pull_request]

env:
  CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
  CIBW_SKIP: cp311-* cp312-*
  CIBW_ARCHS_WINDOWS: "AMD64"
  CIBW_ARCHS_MACOS: "x86_64 arm64"
  CIBW_ARCHS_LINUX: "x86_64"
  CIBW_BEFORE_BUILD_WINDOWS: python .github/workflows/prepare.py && python -m pip install attrdict3
  CIBW_BEFORE_BUILD_MACOS: python -m pip install attrdict3
  CIBW_BEFORE_BUILD_LINUX: python -m pip install attrdict3

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0, windows-2019]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies for macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install fftw
          brew install wxpython

      - name: Install dependencies
        run: python -m pip install attrdict3 wxpython numpy vtk h5py pillow requests

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
      
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: ./wheelhouse/*.whl


  build_sdist:
    name: Build source package
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
  
      - name: Install required Python packages
        run: |
          brew install fftw
          brew install wxpython
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install build
          python -m pip install attrdict3
          python -m pip install wxpython numpy vtk h5py pillow requests

      - name: Build sdist
        run: |
          python -m build --sdist --no-isolation --skip-dependency-check
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
      
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: ./dist/*
